server:
  port: 8083
  servlet:
    # This automatically prefixes EVERY controller in your app
    context-path: /api/v1

spring:
  application:
    name: blog-application

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_blog_service
    username: postgres
    password: Root@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/spring_boot_blog_app
      auto-index-creation: true  # This is required for @Indexed to work

api:
  v1: /api/v1

logging:
  level:
    org:
      springframework:
        security: DEBUG

mail:
  host: smtp.mailtrap.io # or smtp.gmail.com
  port: 2525 # 587 for Gmail
  username: your_username
  password: your_password
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

management:
  server:
    port: 8084
    # Optional: bind to internal network only
    # address: 127.0.0.1

  endpoints:
    web:
      base-path: /manage # Obscurity: hide the fact that you use Actuator
      exposure:
        # Include ONLY what is needed for monitoring (Prometheus/Grafana)
        include: "health,info,prometheus,metrics"

  endpoint:
    health:
      # Show full details only when the user is authorized (authenticated)
      show-details: when_authorized
      probes:
        # CRITICAL: Enables /health/liveness and /health/readiness for K8s
        enabled: true

    env:
      # Mask sensitive passwords/keys in the /env endpoint
      keys-to-sanitize: "password,secret,key,token,.*credentials.*,vcap_services"
      show-values: when_authorized

  info:
    env:
      enabled: true
    git:
      mode: full # Requires git-commit-id-plugin to show git hash/branch
    java:
      enabled: true # Shows JVM version info
